[book]
authors = ["Fuyang Liu"]
language = "en"
multilingual = false
src = "src"
title = "Personal notebook"

[output.html]
git-repository-url = "https://github.com/liufuyang/note"
git-repository-icon = "fa-github"
mathjax-support = true
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
