[book]
authors = ["Fuyang Liu"]
language = "en"
multilingual = false
src = "src"
title = "Personal notebook"
git-repository-url = "https://github.com/liufuyang/note"

[output.html]
mathjax-support = true
